services:
  app-client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client"
    restart: always
    ports:
      - "5173:5173"
    networks:
      - app-network

  app-server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server"
    restart: always
    env_file: ".env"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - VISIO_MONGODB_NAME=${DATABASE_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REALTIME_SERVER_URL=${REALTIME_SERVER_URL}
    ports:
      - "8000:8000"
    networks:
      - app-network

  app-auth-service:
    platform: linux/amd64
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: "auth-service"
    restart: always
    env_file: ".env"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET}
      - DOCKER_COMPOSE_CONFIG=${DOCKER_COMPOSE_CONFIG}
    ports:
      - "3333:3333"
    networks:
      - app-network

  app-realtime-server:
    platform: linux/amd64
    build:
      context: ./realtime-server
      dockerfile: Dockerfile
    container_name: "realtime-server"
    restart: always
    env_file: ".env"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - SERVER_URL=${SERVER_URL}
      - AI_ID=${AI_ID}
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
